export const CATEGORY = {
 SET: 'SET'
}

export const SEARCH = {
 CATEGORY: 'CATEGORY',
 QUERY: 'QUERY'
}

export const NEWS = {
 FETCH: 'FETCH',
 FETCH_SUCCESS: 'FETCH_SUCCESS',
 FETCH_FAIL: 'FETCH_FAIL',

 FETCH_MORE: 'FETCH_MORE',
 FETCH_MORE_SUCCESS: 'FETCH_MORE_SUCCESS',
 FETCH_MORE_FAIL: 'FETCH_MORE_FAIL'
}

export default undefined
